spring.application.name=quizapp
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/question_db
spring.datasource.username=postgres
spring.datasource.password=2909
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.use-root-path=true